### ISSUE TITLE
ModuleNotFoundError: No module named 'pytz'

### ISSUE THREAD

**Issue by meisnate12** [nwithan8/pytulli#8]
## Issue

Looks like a module should probably be added to the requirements. I fixed this in my environment by also installing the module but if pytulli is dependent on it then it should also be installed with pytulli 

## Traceback
```
Traceback (most recent call last):
  File "C:\Users\meisn\Documents\Python\test\main.py", line 2, in <module>
    from tautulli.api import RawAPI
  File "C:\Users\meisn\Documents\Python\test\venv\lib\site-packages\tautulli\api.py", line 1, in <module>
    from tautulli.objectapi import ObjectAPI
  File "C:\Users\meisn\Documents\Python\test\venv\lib\site-packages\tautulli\objectapi.py", line 5, in <module>
    from tautulli.decorators import raw_json, set_and_forget, raw_api_bool, make_object, make_property_object
  File "C:\Users\meisn\Documents\Python\test\venv\lib\site-packages\tautulli\decorators.py", line 4, in <module>
    from tautulli.utils import _success_result, _get_response_data
  File "C:\Users\meisn\Documents\Python\test\venv\lib\site-packages\tautulli\utils.py", line 4, in <module>
    from pytz import timezone
ModuleNotFoundError: No module named 'pytz'
```

**Comment by nwithan8** [comment]
Good catch, I'll roll that in.
